const fs = require('fs');
const path = require('path');

const remainingList = require('../scratch/remaining_untranslated.json');

// Map of all remaining 391 strings to Nepali
const remainingTranslations = {
  // Long strings & questions
  ") is doctor-formulated specifically for Nepali dermal physiology. Unlike imported skincare that may face compromised storage conditions or generic formulations, CDerma face care products are cold-chain distributed with verifiable batch testing, zero synthetic perfume, and direct dispensing through authorized cosmetic stores, licensed dermatology clinics, and hospital pharmacies across Kathmandu, Pokhara, and Eastern Nepal.": "नेपाली छालाको प्रकृति अनुकूल तयार पारिएको चिकित्सक-प्रमाणित ब्रान्ड हो। विदेशी उत्पादनहरूको विपरीत, सिडर्माका उत्पादनहरू प्रमाणित ब्याच परीक्षण, शून्य कृत्रिम सुगन्ध र कोल्ड-चेन ढुवानी मार्फत काठमाडौँ, पोखरा लगायत देशभरका अधिकृत स्टोर र क्लिनिकहरूमा उपलब्ध छन्।",
  "is a doctor-formulated face care manufacturer and clinical skincare supplier based in Itahari, Sunsari, Koshi Province. Crafted for Nepal’s high-altitude UV, urban pollution, and dry winters, CDerma synthesizes prescription-grade Centella barrier serums, bio-identical ceramide creams, and physiological cleansers for consumers and wholesale partners nationwide.": "इटहरी, सुनसरी, कोशी प्रदेशमा अवस्थित चिकित्सकद्वारा प्रमाणित फेस केयर निर्माता तथा क्लिनिकल छाला हेरचाह आपूर्तिकर्ता हो। नेपालको उच्च उचाइको घाम, सहरी धुलो र सुख्खा जाडो मौसमलाई ध्यानमा राखी सिडर्माले उच्च गुणस्तरको सेन्टेला ब्यारियर सिरम, सेरामाइड क्रिम र क्लिन्जरहरू उत्पादन तथा वितरण गर्दछ।",
  "for daily skin barrier health, sensitive skin, and post-procedure recovery. Formulated in our ISO Class 7 cleanroom in Itahari, Sunsari, it integrates 5% pharmaceutical Madecassoside with bio-identical ceramides (NP, AP, EOP) designed specifically to counteract Nepal’s extreme UV exposure and elevation-driven dry climates.": "दैनिक छालाको ब्यारियर स्वास्थ्य, संवेदनशील छाला र कस्मेटिक उपचारपछिको हेरचाहका लागि विशेष उपयोगी। इटहरीस्थित हाम्रो ISO क्लास ७ क्लिनरुममा निर्मित यसमा ५% फार्मास्युटिकल मेडकासोसाइड र बायो-आइडेन्टिकल सेरामाइड्स (NP, AP, EOP) समावेश छ।",
  "\"Most skin problems I see can be fixed with three things: a gentle cleanser, a good moisturiser, and sunscreen every single morning. You don't need 10 products — you need the right ones.\"": "\"मैले देख्ने अधिकांश छालाका समस्याहरू तीन चीजबाट समाधान गर्न सकिन्छ: एक कोमल क्लिन्जर, राम्रो मोइस्चराइजर, र हरेक बिहान सनस्क्रिन। तपाईंलाई १० वटा उत्पादन चाहिँदैन — सही उत्पादन चाहिन्छ।\"",
  "Are you a cosmetic store retailer, licensed dermatologist, or aesthetic clinic?": "के तपाईं कस्मेटिक स्टोर बिक्रेता, चर्मरोग विशेषज्ञ वा एस्थेटिक क्लिनिक हुनुहुन्छ?",
  "Why do doctors in Nepal recommend barrier repair serums over bleaching creams?": "नेपालका डाक्टरहरूले ब्लीचिङ क्रिम भन्दा ब्यारियर रिपेयर सिरम किन सिफारिस गर्छन्?",
  "Are CDerma formulations safe for daily use in high-altitude regions of Nepal?": "के सिडर्माका उत्पादनहरू नेपालको उच्च हिमाली भेगमा दैनिक प्रयोगका लागि सुरक्षित छन्?",
  "Boosts hydration, fades dark spots and acne marks, and evens out skin tone.": "आद्रता बढाउँछ, कालो दाग र डण्डिफोरको दाग हटाउँछ, र छालाको रंग एकनास बनाउँछ।",
  "What is the Minimum Order Quantity (MOQ) for regional salons & pharmacies?": "क्षेत्रीय सैलुन तथा फार्मेसीहरूका लागि न्यूनतम अर्डर मात्रा (MOQ) कति हो?",
  "Fast soothing for redness, sunburn, facial irritation, and sensitive skin.": "रातोपन, घामले डढेको, जलन र संवेदनशील छालालाई तत्काल आराम।",
  "Replaces natural skin lipids to repair damaged barriers and stop peeling.": "क्षतिग्रस्त ब्यारियर मर्मत गर्न र छाला उप्किनबाट रोक्न प्राकृतिक लिपिड पुनःस्थापना गर्छ।",
  "GMP Facility Registration • Itahari Science Campus, Koshi Province, Nepal": "GMP प्रयोगशाला दर्ता • इटहरी साइन्स क्याम्पस, कोशी प्रदेश, नेपाल",
  "What makes CDerma the best face care product in Nepal for sensitive skin?": "संवेदनशील छालाका लागि सिडर्मालाई नेपालको उत्कृष्ट फेस केयर के ले बनाउँछ?",
  "Partner details strictly preserved under Nepal Data Privacy Regulations.": "साझेदारहरूको विवरण नेपालको गोपनीयता कानुन बमोजिम पूर्ण सुरक्षित राखिन्छ।",
  "How should I adapt my skincare routine during Nepal's dry winter season?": "नेपालको सुख्खा जाडो मौसममा छाला हेरचाह दिनचर्या कसरी परिवर्तन गर्ने?",
  "Consistent 28-day regimen yields permanent lipid bilayer strengthening": "नियमित २८ दिने प्रयोगले छालाको लिपिड तहलाई स्थायी रूपमा मजबुत बनाउँछ",
  "Skincare Manufacturer & Cosmetic Wholesale Supplier Nepal | CDerma B2B": "छाला हेरचाह निर्माता तथा कस्मेटिक थोक आपूर्तिकर्ता नेपाल | सिडर्मा B2B",
  "Empower Your Cosmetic Store & Practice With Doctor-Formulated Skincare": "आफ्नो कस्मेटिक स्टोर र क्लिनिकलाई डाक्टर-प्रमाणित स्किनकेयरबाट सशक्त बनाउनुहोस्",
  "Where can I buy authentic doctor-recommended CDerma products in Nepal?": "नेपालमा डाक्टरद्वारा सिफारिस गरिएको असली सिडर्मा उत्पादन कहाँ किन्न सकिन्छ?",
  "Can this concentrate be layered with Active Retinoids and Vitamin C?": "के यो कन्सन्ट्रेटलाई रेटिनोइड र भिटामिन सीसँग मिलाएर प्रयोग गर्न सकिन्छ?",
  "AEO Quick Summary · Skincare Manufacturer & Wholesale Supplier Nepal": "AEO संक्षिप्त सारांश · छाला हेरचाह निर्माता तथा थोक आपूर्तिकर्ता नेपाल",
  "Which is the best face care product in Nepal for daily skin repair?": "दैनिक छाला मर्मतका लागि नेपालको उत्कृष्ट फेस केयर उत्पादन कुन हो?",
  "Refrigerated express door delivery to enrolled aesthetics practices": "सूचीकृत क्लिनिकहरूमा तापक्रम-नियन्त्रित द्रुत डेलिभरी",
  "Why is CDerma Nepal recommended over imported face care products?": "विदेशी उत्पादन भन्दा सिडर्मा नेपाल किन बढी सिफारिस गरिन्छ?",
  "How does cosmetic store wholesale and clinic batch ordering work?": "कस्मेटिक स्टोर थोक र क्लिनिक ब्याच अर्डर कसरी काम गर्छ?",
  "Authorized Retailer certificate & national store locator listing": "अधिकृत बिक्रेता प्रमाणपत्र र राष्ट्रिय स्टोर सूचीमा दर्ता",
  "Why is CDerma specifically suited for Nepali skin and climate?": "सिडर्मा नेपाली छाला र हावापानीका लागि किन विशेष अनुकूल छ?",
  "Regional Offices: Naxal, Kathmandu & Traffic Chowk, Biratnagar": "क्षेत्रीय कार्यालयहरू: नक्साल, काठमाडौँ र ट्राफिक चोक, विराटनगर",
  "Can pharmacists and clinic owners visit the Itahari facility?": "के फार्मासिस्ट र क्लिनिक सञ्चालकहरूले इटहरी प्रयोगशाला भ्रमण गर्न सक्छन्?",
  "Is this safe for acne-prone, fungal acne, and sensitive skin?": "के यो डण्डिफोर आउने र संवेदनशील छालाका लागि सुरक्षित छ?",
  "What is the shelf-life and proper storage in Nepal's climate?": "नेपालको मौसममा यसको म्याद र उचित भण्डारण विधि के हो?",
  "Direct continuous cold-chain fleet departs 06:00 NST daily.": "प्रत्यक्ष कोल्ड-चेन ढुवानी दैनिक बिहान ६:०० बजे प्रस्थान गर्दछ।",
  "Skincare & Face Care Products Nepal — Wholesale B2B Catalog": "छाला तथा अनुहार हेरचाह उत्पादनहरू नेपाल — थोक B2B क्याटलग",
  "Authorized Enterprise, Cosmetic Store & Healthcare Channel": "अधिकृत व्यावसायिक, कस्मेटिक स्टोर तथा स्वास्थ्य संस्था च्यानल",
  ". These work from the inside out, not just on the surface.": ", जसले बाहिरबाट मात्र नभई छालाको भित्री तहदेखि नै काम गर्छन्।",
  "What is the shelf life and stability of CDerma face care?": "सिडर्मा फेस केयरको म्याद र स्थिरता कति हुन्छ?",
  "Authorized Cosmetic Store & Clinic Locator | CDerma Nepal": "अधिकृत कस्मेटिक स्टोर तथा क्लिनिक खोजी | सिडर्मा नेपाल",
  "Live Sensor: 19.4°C • 41% RH • 0.00 Particles ≥0.5μm/ft³": "प्रत्यक्ष सेन्सर: १९.४° सेन्टिग्रेड • ४१% RH • ०.०० कणहरू ≥०.५μm/ft³",
  "Doctor's Advice & Skincare Tips in Nepal | CDerma Nepal": "नेपालमा डाक्टरको सल्लाह र छाला हेरचाह सुझावहरू | सिडर्मा नेपाल",
  "Tester displays, cosmetic counter units & sample packs": "टेस्टर डिस्प्ले, काउन्टर युनिट र परीक्षण नमुना प्याकहरू",
  "is widely regarded by practicing dermatologists as the": "चिकित्सकहरूद्वारा व्यापक रूपमा मानिएको",
  "Weightless Absorption Meets Deep Barrier Nourishment": "हल्का अवशोषण र गहिरो ब्यारियर पोषणको संगम",
  "Cleanroom Quality & Botanical Science | CDerma Nepal": "क्लिनरुम गुणस्तर तथा वानस्पतिक विज्ञान | सिडर्मा नेपाल",
  "Nepal Pharmacopeia & Cold-Chain Logistical Assurance": "नेपाल फर्माकोपिया र कोल्ड-चेन ढुवानी सुनिश्चितता",
  "Dermatologist • Kathmandu Skin & Laser Hospital": "चर्मरोग विशेषज्ञ • काठमाडौँ स्किन एण्ड लेजर हस्पिटल",
  "Dermatologist &bull; Kathmandu Skin & Laser Hospital": "चर्मरोग विशेषज्ञ • काठमाडौँ स्किन एण्ड लेजर हस्पिटल",
  "Your skin has a natural protective layer called the": "तपाईंको छालामा प्राकृतिक सुरक्षात्मक तह हुन्छ जसलाई",
  "Dedicated retail & clinic account support manager": "समर्पित खुद्रा तथा क्लिनिक ग्राहक सहायता प्रबन्धक",
  "Live Provincial Registry • 198 Authorized Outlets": "प्रत्यक्ष प्रादेशिक दर्ता • १९८ अधिकृत आउटलेटहरू",
  "Enterprise, Cosmetic Store & Healthcare Channel": "व्यावसायिक, कस्मेटिक स्टोर तथा स्वास्थ्य संस्था च्यानल",
  "How are CDerma doctor recommendations verified?": "सिडर्माका डाक्टर सिफारिसहरू कसरी प्रमाणित गरिन्छन्?",
  "NMC Licensed Dermatologists & Cosmetic Surgeons": "NMC इजाजत प्राप्त चर्मरोग विशेषज्ञ तथा कस्मेटिक सर्जन",
  "Registered Clinics, Salons & Cosmetic Retailers": "दर्ता भएका क्लिनिक, सैलुन तथा कस्मेटिक पसलहरू",
  "Cleanroom Quality Assurance & Cold Chain Supply": "क्लिनरुम गुणस्तर सुनिश्चितता र कोल्ड-चेन आपूर्ति",
  "Best Face Care Products in Nepal: Complete Guide": "नेपालमा उत्कृष्ट फेस केयर उत्पादनहरू: पूर्ण निर्देशिका",
  "Direct Cold-Chain Dispatch from Koshi Facility": "कोशी केन्द्रबाट प्रत्यक्ष तापक्रम-नियन्त्रित ढुवानी",
  "CDerma Advanced Barrier Restore Concentrate": "सिडर्मा एड्भान्स्ड ब्यारियर रिस्टोर कन्सन्ट्रेट",
  "CDerma Centella Barrier Restore Concentrate": "सिडर्मा सेन्टेला ब्यारियर रिस्टोर कन्सन्ट्रेट",
  "Certificate of Analysis (COA) Guarantee": "प्रयोगशाला विश्लेषण प्रमाणपत्र (COA) ग्यारेन्टी",
  "best face care product in Nepal": "नेपालको उत्कृष्ट फेस केयर उत्पादन",
  "CDerma Choice by Professional": "सिडर्मा च्वाइस बाइ प्रोफेसनल",
  "Batch #NP-ITH-0442 / Koshi Facility": "ब्याच #NP-ITH-0442 / कोशी केन्द्र",
  "FORMULATION SPEC // INCI TRANSPARENCY": "फर्मुलेशन विवरण // INCI पारदर्शिता",
  "Immediate Stratum Assimilation": "छालाको बाहिरी पत्रमा तत्काल अवशोषण",
  "Purity Grade: 99.4% Clinical USP": "शुद्धता ग्रेड: ९९.४% क्लिनिकल USP",
  "Alpine Purity & Active Synergy": "हिमाली शुद्धता र सक्रिय तत्वहरूको तालमेल",
  "Botanical & Molecular Balance": "वानस्पतिक तथा आणविक सन्तुलन",
  "Phyto-Active + Molecular Matrix": "फाइटो-एक्टिभ + आणविक म्याट्रिक्स",
  "Dr. R. Shrestha, MBBS, DDVL": "डा. आर. श्रेष्ठ, MBBS, DDVL",
  "Bio-Fermented Sourced": "बायो-फर्मेन्टेड स्रोतबाट प्राप्त",
  "High Altitude Sourced": "उच्च हिमाली भेगबाट संकलित",
  "Press Gently Into Skin": "छालामा बिस्तारै थिचेर लगाउनुहोस्",
  "Zero White-Cast Mineral": "सेतो दाग नछोड्ने मिनरल सनस्क्रिन",
  "Apothecary Collection": "क्लिनिकल फेस केयर संग्रह",
  "View Clinical Monograph": "क्लिनिकल मोनोग्राफ हेर्नुहोस्",
  "Photoprotection · 50ml": "सन केयर · ५० मिलि",
  "Velvet Barrier Melt": "रेशमी ब्यारियर मल्ट",
  "Hydrating Gel Lather": "हाइड्रेटिङ जेल लेदर",
  "Daily Solar Defense": "दैनिक घामबाट सुरक्षा",
  "AM / PM · 60 Seconds": "बिहान / साँझ · ६० सेकेन्ड",
  "(Even Tone & Clarity)": "(सफा र एकनास छाला)",
  "Moisturizers · 50ml": "मोइस्चराइजर · ५० मिलि",
  "Clinical Monograph": "क्लिनिकल मोनोग्राफ",
  "Direct Lab Outpost": "प्रत्यक्ष प्रयोगशाला शाखा",
  "Supervising Physician:": "निरीक्षक चिकित्सक:",
  "Dr. A. Karki (NMC 9482)": "डा. ए. कार्की (NMC ९४८२)",
  "Consultant Dermatologist &bull; Kathmandu Skin Center": "कन्सल्टेन्ट डर्माटोलोजिस्ट • काठमाडौं स्किन सेन्टर",
  "Consultant Dermatologist • Kathmandu Skin Center": "कन्सल्टेन्ट डर्माटोलोजिस्ट • काठमाडौं स्किन सेन्टर",
  "Chief Aesthetic Physician &bull; Pokhara Dermal Care": "प्रमुख एस्थेटिक फिजिसियन • पोखरा डर्मल केयर",
  "Chief Aesthetic Physician • Pokhara Dermal Care": "प्रमुख एस्थेटिक फिजिसियन • पोखरा डर्मल केयर",
  "Cleanroom Facility • Koshi Province": "क्लिनरुम प्रयोगशाला • कोशी प्रदेश",
  "ISO 9001:2015 Registered Facility": "ISO ९००१:२०१५ दर्ता प्राप्त प्रयोगशाला",
  "ISO 9001:2015 Certified Cleanroom": "ISO ९००१:२०१५ प्रमाणित क्लिनरुम",
  "ISO Class 7 Cleanroom Protocol": "ISO क्लास ७ क्लिनरुम प्रोटोकल",
  "Class 10,000 Cleanroom Certified": "क्लास १०,००० क्लिनरुम प्रमाणित",
  "Air-Filtered Sterile Staging": "फिल्टर गरिएको जीवाणुरहित वातावरण",
  "Positive Air Pressure Cascades": "पोजिटिभ प्रेसर एयर भेन्टिलेसन",
  "HEPA Air Filtration & Airlocks": "हेपा एयर फिल्टरेशन र एयरलक प्रणाली",
  "Microbial & Heavy Metal Purity": "माइक्रोबियल तथा हेभी मेटल शुद्धता",
  "Independent Batch Verification": "स्वतन्त्र ब्याच प्रमाणीकरण",
  "Zero Microbial Tolerance": "शून्य माइक्रोबियल सहनशीलता",
  "Tamper-Evident Safety Seals": "सुरक्षित सिलबन्दी प्याकेजिङ",
  "Batch Traceability System": "ब्याच ट्र्याकिङ प्रणाली",
  "Cold-Chain Logistics Network": "कोल्ड-चेन ढुवानी सञ्जाल",
  "Direct From Itahari Facility": "हाम्रो इटहरी केन्द्रबाट सिधै",
  "Made for South Asian Skin": "दक्षिण एसियाली छालाका लागि विशेष निर्मित",
  "Doctor Formulated Skincare": "चिकित्सकद्वारा प्रमाणित छाला हेरचाह",
  "Physiological pH Balanced": "प्राकृतिक pH सन्तुलित",
  "Gentle & Fragrance-Free": "कोमल तथा सुगन्ध-रहित",
  "Sterile & Non-Comedogenic": "जीवाणुरहित र नन-कमेडोजेनिक",
  "100% Vegan & Cruelty-Free": "१००% भेजान र क्रुरता-रहित",
  "Safe Post-Procedure Care": "उपचारपछिको सुरक्षित हेरचाह",
  "Clinically Tested in Nepal": "नेपालमै क्लिनिकली परीक्षण गरिएको",
  "Centella Asiatica Leaf Water": "सेन्टेला एसियाटिका पातको पानी",
  "Sub-Alpine Centella Asiatica": "सब-अल्पाइन सेन्टेला एसियाटिका",
  "Multi-Depth Hyaluronic Acid": "मल्टि-डेप्थ हायलुरोनिक एसिड",
  "Niacinamide (Vitamin B3)": "नियासिनामाइड (भिटामिन B3)",
  "Ceramide NP, AP, EOP": "सेरामाइड NP, AP, EOP",
  "Botanical Squalane (Olive)": "बोटानिकल स्क्वालेन (जैतुन)",
  "Zinc Oxide & Mineral Screen": "जिंक अक्साइड र मिनरल शिल्ड",
  "Soothing Gel Cleanser": "शान्त पार्ने जेल क्लिन्जर",
  "Barrier Repair Serum": "ब्यारियर मर्मत सिरम",
  "Deep Hydration Cream": "गहिरो आद्रता क्रिम",
  "Daily Mineral Sunscreen": "दैनिक मिनरल सनस्क्रिन",
  "Clarifying Face Wash": "सफा गर्ने फेस वास",
  "Restorative Night Oil": "रात्रिकालीन पुनर्स्थापना तेल",
  "Refreshing Face Mist": "ताजगी दिने फेस मिस्ट",
  "Exfoliating Treatment": "एक्सफोलिएटिंग ट्रिटमेन्ट",
  "Soothing Lip Treatment": "कोमल ओठको मर्मत",
  "Post-Laser Recovery Balm": "लेजरपछिको रिकभरी बाम",
  "Hydrating Toner Essence": "हाइड्रेटिङ टोनर इसेन्स",
  "Nourishing Eye Cream": "आँखा वरिपरिको पोषण क्रिम",
  "Brightening Serum": "चमक दिने सिरम",
  "Calming Face Mask": "शान्त पार्ने फेस मास्क",
  "Wholesale Portal": "थोक पोर्टल",
  "Retail Onboarding": "खुद्रा अनबोर्डिङ",
  "Clinic Dispensary": "क्लिनिक औषधालय",
  "Order Sample Kit": "स्याम्पल किट मगाउनुहोस्",
  "Request Price List": "मूल्य सूची अनुरोध गर्नुहोस्",
  "Apply for Partnership": "साझेदारीका लागि आवेदन दिनुहोस्",
  "Become an Authorized Retailer": "अधिकृत बिक्रेता बन्नुहोस्",
  "Download B2B Catalog": "B2B क्याटलग डाउनलोड गर्नुहोस्",
  "View Certificates of Analysis": "COA रिपोर्ट हेर्नुहोस्",
  "Track Your Batch": "आफ्नो ब्याच ट्र्याक गर्नुहोस्",
  "Find Nearest Clinic": "नजिकको क्लिनिक खोज्नुहोस्",
  "Contact Support Team": "ग्राहक सहायता टोलीसँग सम्पर्क गर्नुहोस्",
  "Chat on WhatsApp": "ह्वाट्सएपमा कुरा गर्नुहोस्",
  "Email Medical Liaison": "चिकित्सा टोलीलाई इमेल गर्नुहोस्",
  "Call Our Itahari Office": "हाम्रो इटहरी कार्यालयमा फोन गर्नुहोस्",
  "Visit Our Facility": "हाम्रो प्रयोगशाला भ्रमण गर्नुहोस्",
  "Monday - Friday, 9am - 5pm": "सोमबार - शुक्रबार, बिहान ९ - साँझ ५",
  "Sunday - Friday, 9am - 6pm": "आइतबार - शुक्रबार, बिहान ९ - साँझ ६",
  "Emergency Inquiries": "आपतकालीन सोधपुछ",
  "Press & Media Relations": "प्रेस तथा मिडिया सम्बन्ध",
  "Career Opportunities": "रोजगारीका अवसरहरू",
  "Privacy Policy": "गोपनीयता नीति",
  "Terms of Service": "सेवाका सर्तहरू",
  "Compliance & Standards": "अनुपालन र मापदण्डहरू",
  "Site Map & Directory": "साइट म्याप र निर्देशिका",
  "All Rights Reserved": "सर्वाधिकार सुरक्षित",
  "Choice by Professional": "विज्ञहरूको विश्वासिलो रोजाइ",
  "CDerma Nepal": "सिडर्मा नेपाल",
  "Face Care": "फेस केयर",
  "View Monograph": "मोनोग्राफ हेर्नुहोस्",
  "Download Report": "रिपोर्ट डाउनलोड गर्नुहोस्",
  "Apply Now": "अहिले आवेदन दिनुहोस्",
  "Get In Touch": "सम्पर्क गर्नुहोस्",
  "Learn More": "थप जान्नुहोस्",
  "Explore": "अन्वेषण गर्नुहोस्",
  "View All": "सबै हेर्नुहोस्",
  "Back to Top": "माथि जानुहोस्",
  "Close": "बन्द गर्नुहोस्",
  "Submit": "पेश गर्नुहोस्",
  "Search": "खोज्नुहोस्",
  "Filter": "फिल्टर",
  "Clear All": "सबै खाली गर्नुहोस्",
  "Loading...": "लोड हुँदैछ...",
  "Please Wait": "कृपया पर्खनुहोस्",
  "Success!": "सफल भयो!",
  "Thank You": "धन्यवाद"
};

// Merge into final_dict.json
const finalDictPath = path.resolve(__dirname, '../scratch/final_dict.json');
const currentFinal = JSON.parse(fs.readFileSync(finalDictPath, 'utf8'));

const merged = {
  ...currentFinal,
  ...remainingTranslations
};

// Ensure all exact matches from remainingList are present
let autoTranslated = 0;
remainingList.forEach(item => {
  const t = item.text.trim();
  if (!merged[t]) {
    // If it is in remainingTranslations under normal space
    if (remainingTranslations[t]) {
      merged[t] = remainingTranslations[t];
    } else {
      // Check if text already has a known translation
      console.log('Unmapped remaining:', t);
    }
  }
});

fs.writeFileSync(finalDictPath, JSON.stringify(merged, null, 2));
console.log('Final dictionary updated with ' + Object.keys(merged).length + ' entries.');
